// Code generated by MockGen. DO NOT EDIT.
// Source: providers/controlplane/types.go
//
// Generated by this command:
//
//	mockgen-v0.4.0 -destination=providers/controlplane/mock/mock_controlplane.go -source=providers/controlplane/types.go
//

// Package mock_controlplane is a generated GoMock package.
package mock_controlplane

import (
	providers "capi-bootstrap/providers"
	yaml "capi-bootstrap/yaml"
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockProvider is a mock of Provider interface.
type MockProvider struct {
	ctrl     *gomock.Controller
	recorder *MockProviderMockRecorder
}

// MockProviderMockRecorder is the mock recorder for MockProvider.
type MockProviderMockRecorder struct {
	mock *MockProvider
}

// NewMockProvider creates a new mock instance.
func NewMockProvider(ctrl *gomock.Controller) *MockProvider {
	mock := &MockProvider{ctrl: ctrl}
	mock.recorder = &MockProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProvider) EXPECT() *MockProviderMockRecorder {
	return m.recorder
}

// GenerateAdditionalFiles mocks base method.
func (m *MockProvider) GenerateAdditionalFiles(ctx context.Context, values providers.Values) ([]yaml.InitFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateAdditionalFiles", ctx, values)
	ret0, _ := ret[0].([]yaml.InitFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateAdditionalFiles indicates an expected call of GenerateAdditionalFiles.
func (mr *MockProviderMockRecorder) GenerateAdditionalFiles(ctx, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateAdditionalFiles", reflect.TypeOf((*MockProvider)(nil).GenerateAdditionalFiles), ctx, values)
}

// GenerateCapiFile mocks base method.
func (m *MockProvider) GenerateCapiFile(ctx context.Context, values providers.Values) (*yaml.InitFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateCapiFile", ctx, values)
	ret0, _ := ret[0].(*yaml.InitFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateCapiFile indicates an expected call of GenerateCapiFile.
func (mr *MockProviderMockRecorder) GenerateCapiFile(ctx, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateCapiFile", reflect.TypeOf((*MockProvider)(nil).GenerateCapiFile), ctx, values)
}

// GenerateInitScript mocks base method.
func (m *MockProvider) GenerateInitScript(ctx context.Context, initScriptPath string, values providers.Values) (*yaml.InitFile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateInitScript", ctx, initScriptPath, values)
	ret0, _ := ret[0].(*yaml.InitFile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateInitScript indicates an expected call of GenerateInitScript.
func (mr *MockProviderMockRecorder) GenerateInitScript(ctx, initScriptPath, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateInitScript", reflect.TypeOf((*MockProvider)(nil).GenerateInitScript), ctx, initScriptPath, values)
}

// GenerateRunCommand mocks base method.
func (m *MockProvider) GenerateRunCommand(ctx context.Context, values providers.Values) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateRunCommand", ctx, values)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GenerateRunCommand indicates an expected call of GenerateRunCommand.
func (mr *MockProviderMockRecorder) GenerateRunCommand(ctx, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateRunCommand", reflect.TypeOf((*MockProvider)(nil).GenerateRunCommand), ctx, values)
}

// PreDeploy mocks base method.
func (m *MockProvider) PreDeploy(ctx context.Context, values *providers.Values) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PreDeploy", ctx, values)
	ret0, _ := ret[0].(error)
	return ret0
}

// PreDeploy indicates an expected call of PreDeploy.
func (mr *MockProviderMockRecorder) PreDeploy(ctx, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PreDeploy", reflect.TypeOf((*MockProvider)(nil).PreDeploy), ctx, values)
}

// UpdateManifests mocks base method.
func (m *MockProvider) UpdateManifests(ctx context.Context, manifests []string, values providers.Values) (*yaml.ParsedManifest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateManifests", ctx, manifests, values)
	ret0, _ := ret[0].(*yaml.ParsedManifest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UpdateManifests indicates an expected call of UpdateManifests.
func (mr *MockProviderMockRecorder) UpdateManifests(ctx, manifests, values any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateManifests", reflect.TypeOf((*MockProvider)(nil).UpdateManifests), ctx, manifests, values)
}
