---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeadm-bootstrap-system
---
apiVersion: v1
kind: Namespace
metadata:
  name: kubeadm-control-plane-system
---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: BootstrapProvider
metadata:
  name: kubeadm
  namespace: kubeadm-bootstrap-system
spec:

---
apiVersion: operator.cluster.x-k8s.io/v1alpha2
kind: ControlPlaneProvider
metadata:
  name: kubeadm
  namespace: kubeadm-control-plane-system
spec: