cluster-init: true
flannel-backend: none
disable-network-policy: true
disable-cloud-controller: true
disable:
  - servicelb
  - traefik
kube-apiserver-arg:
  - anonymous-auth=true
  - tls-cipher-suites=TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384,TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305,TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305,TLS_RSA_WITH_AES_128_GCM_SHA256,TLS_RSA_WITH_AES_256_GCM_SHA384
kube-controller-manager-arg:
  - cloud-provider=external
kubelet-arg:
  - cloud-provider=external
node-name: '{{{ .ClusterName }}}-bootstrap'
node-ip:
tls-san:
  - {{{ .Linode.NodeBalancerIP }}}
