---
apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  namespace: kube-system
  name: ccm-linode
spec:
  targetNamespace: kube-system
  version: v0.4.10
  chart: ccm-linode
  repo: https://linode.github.io/linode-cloud-controller-manager/
  bootstrap: true
  valuesContent: |-
    routeController:
      vpcName: {{{ .ClusterName }}}
      clusterCIDR: 10.0.0.0/8
      configureCloudRoutes: true
    secretRef:
      name: 'linode-token-region'
    image:
      pullPolicy: IfNotPresent
    secretRef:
      name: 'linode-token-region'
    nodeSelector:
      node-role.kubernetes.io/control-plane: "true"
---
kind: Secret
apiVersion: v1
metadata:
  name: linode-token-region
  namespace: kube-system
stringData:
  apiToken: "{{{ .Linode.Token }}}"
  region: "{{ ds.meta_data.region }}"
