---
apiVersion: cluster.x-k8s.io/v1beta1
kind: Machine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "[[[ .ClusterName ]]]"
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: ""
  name: "[[[ .ClusterName ]]]-bootstrap"
  namespace: default
spec:
  bootstrap:
    dataSecretName: linode-[[[ .ClusterName ]]]-crs-0
  infrastructureRef:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: LinodeMachine
    name: "[[[ .ClusterName ]]]-bootstrap"
    namespace: default
  clusterName: "[[[ .ClusterName ]]]"
  providerID: linode://{{ ds.meta_data.id }}
  version: "[[[ .K8sVersion ]]]"
  [[[- if .SSHAuthorizedKeys ]]]
  authorizedKeys:[[[ range .SSHAuthorizedKeys ]]]
    - [[[ . ]]][[[ "\n" ]]]
  [[[- end -]]]
  [[[- end -]]]
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: LinodeMachine
metadata:
  labels:
    cluster.x-k8s.io/cluster-name: "[[[ .ClusterName ]]]"
    cluster.x-k8s.io/control-plane: ""
    cluster.x-k8s.io/control-plane-name: ""
  name: "[[[ .ClusterName ]]]-bootstrap"
  namespace: default
spec:
  image: linode/ubuntu22.04
  instanceID: {{ ds.meta_data.id }}
  providerID: "linode://{{ ds.meta_data.id }}"
  region: "{{ ds.meta_data.region }}"
  type: g6-standard-6
  [[[- if .SSHAuthorizedKeys ]]]
  authorizedKeys:[[[ range .SSHAuthorizedKeys ]]]
    - [[[ . ]]][[[ "\n" ]]]
  [[[- end -]]]
  [[[- end -]]]
